### ISSUE TITLE
Auto update slider not working?

### ISSUE THREAD

**Issue by jaimsitecom** [umbrellaplug/umbrellaplug.github.io#122]
I noticed Umbrella not checking and updating library anymore. Tried changing the default frequency of library updates service interval from the default of 6 to 3 and then now to 1, none works. I had to manually click ‘update library’ from the Library settings of Umbrella. On top of this, before, umbrella checks and updates the Library EVERYTIME kodi starts up, now it doesn’t do it anymore thus the manual clicking of the update button is necessary. 

Should we also ditch the slider and revert  back to the old no slider and just default on checking everytime kodi starts and checks again every 6hrs interval? That old one (no slider) works well. 

thanks.

**Comment by umbrellaplug** [comment]
It's working on my side. I moved the library episode update into the list update function to only run if the number of new results detected on a list are greater than 0. I plan on looking into the library bugs this weekend so hopefully I can resolve your already exists in library error. The slider is working for me though. Is there something you've added you're not seeing added to the library that is indicating to you it's not working?

**Comment by jaimsitecom** [comment]
Oh ok. I guess it’s my machine only. I wonder what changed?  It won’t check/update anymore whenever i turn on kodi. 

I will try to change my tv info provider from TMDB TV SHOWS to TVDB v4. i really have a feeling TMDB info scraper is conking out. 

Anyways, i’ll tinker some more and gove updates too. Thanks so much!

**Comment by jaimsitecom** [comment]
I’ll try to downgrade again to the pre-slider version and see if it will bring back the automatic updating for me.

**Comment by jaimsitecom** [comment]
Downgraded back to ver 6.5.75 then changed my tv info provider from ‘tmdb tv shows’ to ‘tvdb v4’. You are correct, it’s a bug alright. Error popup appearing still and erratic adding of tv shows still a problem. Also, no umbrella auto check for new  tv show episodes at kodi startup. Don’t know why it disappeared or why it stopped doing it. Haven’t installed any new addons for months.

**Comment by umbrellaplug** [comment]
Can you get your logs and post them? I'd like to see if there's any indications there as to what may be happening. I have some time to look at the library stuff today, but I'm not experiencing some of the issues you are. Any logs or steps to duplicate the issues you're having you could provide would be helpful.

**Comment by jaimsitecom** [comment]
Sorry forgot to paste these logs when it was still on ver 6.5.75:

umbrella log - https://paste.kodi.tv/yuroluvila

kodi log - https://paste.kodi.tv/ixusagoxal

I’ll post logs for ver 6.5.80 next. Ty

**Comment by jaimsitecom** [comment]
> Can you get your logs and post them? I'd like to see if there's any indications there as to what may be happening. I have some time to look at the library stuff today, but I'm not experiencing some of the issues you are. Any logs or steps to duplicate the issues you're having you could provide would be helpful.

Does umbrella still auto update and look for new episodes when you start kodi? A couple versions ago, i usually see an umbrella popop notifivation that it it updating the library. Nowadays it doesn’t show up whenever kodi starts. Or does it do it in the background w/o notifications anymore?

**Comment by umbrellaplug** [comment]
It just depends on your settings. There's service update pop ups and general notifications in settings > library. If you have those turned off it's likely silently updating.

**Comment by jaimsitecom** [comment]
> It just depends on your settings. There's service update pop ups and general notifications in settings > library. If you have those turned off it's likely silently updating.
Those settings are both checked ever since, never unchecked those coz i always wanna see what’s goin on. But now only popup notifications i get are thos ‘umbrella error’ and ‘titoe already exists’ popups.

**Comment by jaimsitecom** [comment]
Updated back to 6.5.80

1. Restarted kodi, didn’t get umbrella’s library update popup/notification
2. I deleted a tv show (midnight club), cleaned the library
3. Went inside umbrella to search for ‘midnight club’ tv series
4. Went to context menu to add the show, popup came up saying title already exist in library. Even if i’ve deleted and cleaned the database already

ty

**Comment by jaimsitecom** [comment]
Also noticed, when i use the clean library setting inside umbrella, after doin such, the gear just rotates forever, always have to click ‘back button’ to stop it after waiting for more than 5mins. I always had to use Kodi’s clean library function in its settings and it takes less than a minute to do it. 

Ty

**Comment by jaimsitecom** [comment]
Hi again. Upgraded to 6.5.85, but  still no joy on Umbrella’s AUTO UPDATE SERVICE when opening Kodi. When i downgraded to the pre slider option (ver 6.5.75), Umbrellas Auto update triggers whenever i start Kodi. But ever since the slider for Update interval and the now gone/remove delay slider, it disappeared for me. I even turned off reuselangiageinvoker option but still no joy. 

Kodi log:
https://mega.nz/file/kYxQkL5I#hSqUddnpCB0muCQH5ZFRCTyDQB_XRl17UJLYIlFOjS8

Umbrella log:
https://mega.nz/file/UNAmGIzL#8OOTLH-TXMvb8Viu0pSHianZspWpaBl28JOkVP7qeqY

I had all service notifications turned on but i see it not updating everytime i start kodi. TMDB HELPER’s auto update turns on when kodi starts. So is the Promise’s.  Only Umbrella’s got broken i think. 

I hope the logs shows the root of the problem. Ty

**Comment by umbrellaplug** [comment]
These partial logs you keep adding are not helpful. They show a couple of irrelevant lines to what you are asking about or are blank.

Follow the steps outlined here to get debug logs from the addon.
https://github.com/umbrellaplug/umbrellaplug.github.io/wiki#logs

**Comment by jaimsitecom** [comment]
> These partial logs you keep adding are not helpful. They show a couple of irrelevant lines to what you are asking about or are blank.
> 
> Follow the steps outlined here to get debug logs from the addon. https://github.com/umbrellaplug/umbrellaplug.github.io/wiki#logs

But i followed the guide and i wonder why umbrella says no logs created because I didn’t have it enabled, but it’s enabled. So that’s why i had to extract the logs via file explorer. I’ll try again. Sorry about that.

**Comment by jaimsitecom** [comment]
Is it possible that my umbrella addon is corrupted/damaged thus ‘no updating’?  Always had to manually do it just to get bew episodes. Will a clean install help?

**Comment by umbrellaplug** [comment]
I'd say anything is possible. The fact that the slider isn't working for you but is for everyone else indicates something may be wrong with settings.xml. Not sure, I would try a fresh load if it isn't a huge amount of trouble.

**Comment by jaimsitecom** [comment]
I give up on this issue of mine for now. I’ve uninstalled Umbrella completely, then installed clean/fresh. Re-entered all infos inside accounts, re-set up all needed setting features… And yet, Umbrella still won’t AUTO LIBRARY UPDATE when kodi starts. So frustrating not knowing how i messed that option up. Hehehe

If i open the settings xml, is there a specific line i should look out for that enables/disables this specific feature of library updating when kodi starts?  

So sorry for this, the OC in me wanted to bring back that simple old feature that is so important to me. 

Only brightside is at least i can still manually click the update library inside Umbrella’s library settings. But still… Sigh. 😜

**Comment by umbrellaplug** [comment]
If I give you an advanced settings xml file do you have the ability to place it in your userdata folder? I can give you an advanced settings file to use with increased logging that should tell us from the logs what your issue is.

**Comment by jaimsitecom** [comment]
> 

Oh yes please. I would appreciate that. Ty!

**Comment by umbrellaplug** [comment]
[advancedsettings.zip](https://github.com/umbrellaplug/umbrellaplug.github.io/files/10031645/advancedsettings.zip)

Unzip that file and frop advancedsettings.xml into your userdata folder on kodi. Change your settings in umbrella to log to the kodi.log instead of the umbrella.log. Restart kodi, retry the library update that's giving you issues, then grab the kodi.log from that same folder and send it to me. 

If you're unable to get the file loaded correctly you could manually create an advancedsettings.xml and set it like this:
`<advancedsettings>
 <loglevel>1</loglevel>
</advancedsettings>`

Being very transparent here, do not leave your setup like this. It adds a huge amount of logging for debugging. Once you get the logs and everything I would just delete the advancedsettings.xml file. I personally leave mine like this, but it's hard on your system.

**Comment by jaimsitecom** [comment]
Got it!  Should i save the current advancedsettings.xml inside userdata folder? Then put it back once we’ve used yours and have gotten the data we needed?

**Comment by umbrellaplug** [comment]
Yeah, if you're currently already using an advanced settings you could keep it there and just add that <loglevel>1</loglevel> to it then remove it when your done. However you want to do it. That is an interesting topic though, if you're using advancedsettings.xml already what settings do you have set there now?

**Comment by jaimsitecom** [comment]
one thing though... my main problem is kinda hard to replicate... as i've stated earlier, the issue is that UMBRELLA'S AUTO LIBRARY UPDATE that usually happens during kodi startup/bootup doesn't seem to get triggered to load anymore.  And even if i set the interval service to check every hour, nothing comes up as i've sat myself in front of kodi for a couple of hours just to check if AUTO LIBRARY UPDATE will pop up and work again... but nada.  Anyways, i've inserted the advancesettings.xml into the userdata folder of kodi... setup the logging to be kodi.log instead of umbrellas too. will wait several minutes for an Umbrella popup error (i suspect it's the error that causes the update service to not push thru... i think but maybe not also :))

anyways, once i've gathered some data via log, i'll send it back here via umbrellas pastebin for logs.

thanks again!

**Comment by umbrellaplug** [comment]
Okay, please remember to get the kodi.log not the umbrella log. If you need a version with more logging added for debugging after this I can write some more logging into the addon and send you a special version. I suspect the error is likely a cause/ contributor to the problem as well. What does the error say?

**Comment by jaimsitecom** [comment]
> Yeah, if you're currently already using an advanced settings you could keep it there and just add that `<loglevel>1</loglevel>` to it then remove it when you're done. However you want to do it. That is an interesting topic though, if you're using advancedsettings.xml already what settings do you have set there now?

this is what's inside the current advancesettings.xml 

<advancedsettings>
    <cache>
        <buffermode>1</buffermode>
        <memorysize>157286400</memorysize>
        <readfactor>10</readfactor>
    </cache>
</advancedsettings>

**Comment by jaimsitecom** [comment]
ok, i went inside Umbrella settings and tried to view what's inside kodi log, and then i went back out to kodi's tv library. and then i saw that there's an entry in the playlist... 'VIEW KODI LOG'

is that normal? why is that action put into the video playlist? hehe so weird... i think all these umbrella pop up errors are due to the fact that unplayable items are put into the video playlist... hmmmmm really strange.

**Comment by jaimsitecom** [comment]
Wait... am i asking the wrong question?  let me understand first, is UMBRELLA'S AUTO LIBRARY UPDATE still active for Non-build/widget umbrella users?  I am just a kodi user with umbrella addon used for adding movies and tv shows into kodi's library.  Maybe i am asking for is taken out/removed already? hehehe sorry so confused and frustrated.  From my understanding and experience, the library update via umbrella during kodi startup was still active in versions 6.5.69 to 75? if i am not mistaken... and once the sliders were implemented (6.5.80?), i noticed that the startup library update via umbrella was gone, for my machine at least. i just wanna make sure we are both talking about the same thing... ty

**Comment by jaimsitecom** [comment]
Ok, so still no kodi startup umbrella library update happened. I went in and out of umbrella just to trigger something to make it vome up with error. So far only thing weird was those entries into the playlist. Got impatient and tried to do a manual umbrella ibrary update, it went thru it normally until it popped up an umbrella error right before another notification that says library update is complete. Happened around 10:52pm Nov 17 in log. 

You don’t kid alright. For just several minutes, log has accumulated a lot already and still goin! Hehehe

**Comment by jaimsitecom** [comment]
> Can you send me that log?

https://mega.nz/file/4YAFzCIY#qs4MH7GjGERGFZfZafaHpdi-kjAAphbLI0nVCEa8BgE

**Comment by umbrellaplug** [comment]
Alright, sorry for the delay had to really look over that. You've got a large amount of errors there. Open Wizard is having problems, trakt is having issues, tmdbhelper is having issues. you are getting connection timeout, and max retry errors. The umbrella error popup is due to the changes we made for the logs caused them to be too large to upload.

**Comment by jaimsitecom** [comment]
Wow. Ok first maybe i should uninstall open wizard. Trakt and tmdbhelper we cannot do anything. 

The timeout and retry errors, how do i tinker with that?  

But all these don’t say anything why the umbrella auto library update is gone, right? Sigh. 

Thanks for everything man.

**Comment by jaimsitecom** [comment]
Ok so i’ve decided to downgrade and stick to an old version (6.5.69) that works for me. I just don’t know why the succeeding versions stopped the auto check when kodi starts up. But anyways, thanks for all the help. When there’s a new release, i’d still try it since i can always downgrade to the ones that work for me. Ty so much!

**Comment by umbrellaplug** [comment]
Ok. Whatever works for you. I hate you're having issues with the updates. I didn't see a clear reason in the logs, but you've got a lot of errors. I see you're doing library imports with tmdbhelper also. There may a conflict there. I can give you a version with a little more logging as well. I'll compare the changes from 6.5.69 to 6.5.85 and see if I can find anything.

**Comment by jaimsitecom** [comment]
Man, ty so much! You’re such a gift. You’re the only developer I’ve come across who do really help out users like me. 

I am also suspecting that TMDB HELPER’s new updates could’ve conflicted with whatever. I only use TMDB H to facilitate video playing for FEN, so that i have an alternative if Umbrella couldn’t scrape a movie/show or what not. 

Again, i appreciate everything and all the assistance from you. Thanks so much!

**Comment by umbrellaplug** [comment]
Can you make sure you are on the latest version of tmdbhelper from jurials alpha repo?

Also, can you try deleting your library.db from the userdata/addons/plugin.video.umbrella folder and restarting your kodi?

Neither of these should cause you to lose anything. I'll be looking into the different versions to see if I can find anything that I might have done to cause you problems today.

**Comment by jaimsitecom** [comment]
> Can you make sure you are on the latest version of tmdbhelper from jurials alpha repo?
> 
> Also, can you try deleting your library.db from the userdata/addons/plugin.video.umbrella folder and restarting your kodi?
> 
> Neither of these should cause you to lose anything. I'll be looking into the different versions to see if I can find anything that I might have done to cause you problems today.

Nice!  The deleting of library.db worked well on weeding out which version has the AUTO LIBRARY UPDATE not working.

So far, versions:
6.5.69
6.5.72
6.5.73
6.5.74 and
6.5.75

all the versions above worked and were pre-slider versions for auto update and interval/frequency checks. Meaning after the implementation of sliders (starting 6.5.76 up to current 6.5.85) the AUTO UPDATE when kodi starts stopped working. 

Hope these data helps you somewhat. 

Thanks again for these tips.

**Comment by umbrellaplug** [comment]
I stand by my slider. :)

In all seriousness though, it's not the slider. Just so happens that was added at the same time as another change. I think I found your issue and I've pushed a new version to the test repo. If you could, can you load that version and clear your lists from the import manager window or delete the library.db one more time, then try to load them and see if updates occur. You will only get a notification if a new item has been added.

The test repo is loaded just like the original repo. 
Add Source > https://umbrellaplug.github.io/umbrellatest
You can then add the test repository from there and should be a version 6.5.86 available now. Please let me know your results.

**Comment by jaimsitecom** [comment]
> I stand by my slider. :)
> 
> In all seriousness though, it's not the slider. Just so happens that was added at the same time as another change. I think I found your issue and I've pushed a new version to the test repo. If you could, can you load that version and clear your lists from the import manager window or delete the library.db one more time, then try to load them and see if updates occur. You will only get a notification if a new item has been added.
> 
> @jaimsitecom The test repo is loaded just like the original repo. Add Source > https://umbrellaplug.github.io/umbrellatest You can then add the test repository from there and should be a version 6.5.86 available now. Please let me know your results.

Hahahah

will surely test this out. Ty!

**Comment by jaimsitecom** [comment]
Ok. 
1. Installed the test umbrella version.
2. Exited kodi
3. Deleted the library.db
4. Started kodi
5. So far, 30mins in after kodi started, library update hasn’t been triggered. No action from umbrella.

**Comment by jaimsitecom** [comment]
Yep, new test version still wont Auto Update for me after more than 2 hrs of waiting. Had to go downgrade back to 6.5.75. The moment i downgraded and restarted kodi, AUTO UPDATE worked. 😃

this version 6.5.75 works fine with me. am ok staying stuck here if that'll be the case and i am the only one with this problem. 

thanks!

**Comment by umbrellaplug** [comment]
> Yep, new test version still wont Auto Update for me after more than 2 hrs of waiting. Had to go downgrade back to 6.5.75. The moment i downgraded and restarted kodi, AUTO UPDATE worked. 😃
> 
> 
> 
> this version 6.5.75 works fine with me. am ok staying stuck here if that'll be the case and i am the only one with this problem. 
> 
> 
> 
> thanks!

Thanks for trying that one. I had two places where code changes were made for imports. I'll make a change and let you know when there's a new version to try again. It's early AM here so it will be a few hours.

**Comment by jaimsitecom** [comment]
> > Yep, new test version still wont Auto Update for me after more than 2 hrs of waiting. Had to go downgrade back to 6.5.75. The moment i downgraded and restarted kodi, AUTO UPDATE worked. 😃
> > this version 6.5.75 works fine with me. am ok staying stuck here if that'll be the case and i am the only one with this problem.
> > thanks!
> 
> Thanks for trying that one. I had two places where code changes were made for imports. I'll make a change and let you know when there's a new version to try again. It's early AM here so it will be a few hours.

Thanks a lot!

**Comment by umbrellaplug** [comment]
Can you try version .88 and let me know.

**Comment by jaimsitecom** [comment]
> Can you try version .88 and let me know.

Wow this one’s (6.5.88) auto library check worked! Yahoo!

Now i will monitor the service interval checking if this version’s will work. I noticed .75’s won’t re-check after 6hrs. And also won’t auto library check the next day unless i delete the library.db. 

Ver .69 seems the most consistent in auto check library with constant 6hrs interval checking. 

Hope ver .88 will be good too. I’ve put the interval to an hourly check. I’ll report it next. 

Thanks again!

**Comment by jaimsitecom** [comment]
Yes!!! Success!

ver …88 is great!  
1. Checked and auto updated library when kodi started 
2. Checked and updated library hourly interval (i used the slider) 😀
3. 2 straight hourly checked and updated a success. 

Thanks so much!!!

**Comment by umbrellaplug** [comment]
Great. I will push these changes in the next update. Sorry for the back and forth I appreciate you taking the time to help me get this resolved.

**Comment by jaimsitecom** [comment]
> Great. I will push these changes in the next update. Sorry for the back and forth I appreciate you taking the time to help me get this resolved.

Don’t apologize. I am the one who should be apologizing for bugging you on this. I appreciate all your work. Ty so much!
